name : workflow

on :
  psuh :
    branch :
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integration :
    name : Continuos-Integration
    runs-on : ubuntu-latest
    steps : 
      - name : Checkout Code
        uses : actions/checkout@v3

      - name : Lint code
        run : acho "Linting repository"

      - name : Run unit tests
        run : echo "Running unit tests"
